.TH TUXMATH 6 "Dec 17, 2004" "Fabio Brito"

.SH NAME
tuxmath \- a math game for kids with Tux

.SH DESCRIPTION
 "Tux, of Math Command" ("TuxMath," for short) is an
 educational arcade game starring Tux, the Linux mascot!
 Based on the classic arcade game "Missile Command," Tux
 must defend his cities. In this case, though, he must do
 it by solving math problems.

.SH OPTIONS
.TP
.B \-\-help
Display help for the command
.TP
.B \-\-version
Display version and author information

.SH HISTORY
Dec 17 2004: First version of this manual page.

.SH AUTHOR
This manual page was written by
Fabio Brito <\fIfabio@debian-ba.org\fP>
for the Debian GNU system (but may be used by others).
