#ifndef CAMPAIGN_H
#define CAMPAIGN_H

#include "tuxmath.h"
#include "credits.h"
#include "titlescreen.h"
#include "SDL_extras.h"
#include "game.h"
#include "fileops.h"

#define TESTING_CAMPAIGN

#define NUM_STAGES 5 
#define NUM_ROUNDS 3


static char* briefings[NUM_STAGES][100] = {
  //cadet
  {
    "-[Esc] to skip",
    "Mission One: Careful Cadet",
    "--------------------------",
    "Welcome, Tux!",
    "",
    "Congratulations on your graduation from the ",
    "Math Command Training Acedemy. ",
    "",
    "Your arrival to the Galactic Math Command Fleet",
    "comes just in time. The distant star Mathematica",
    "has gone supernova, and parts of its solar",
    "system are now traveling toward the planet FOSS.",
    "",
    "Mathematican asteroids are made of a material",
    "called Undotrium, a mysterious metal that is",
    "known to be very hard to destroy. But Galactic",
    "scientists think they have found a way to do",
    "so. Powerful computers connected to a Lambda",
    "Laser can use numbers to locate Undotrium comets,",
    "aim and shoot a perfect beam that will turn it",
    "into harmless snow. But first, you need to look",
    "closely at the comet and tell the Lambda Laser",
    "Computer what number it needs to use. There are",
    "many different types of comets, and it is up to",
    "up to you to figure out these numbers!",
    "",
    "Tux, your first mission as a Cadet will be to",
    "help the peaceful penguins of FOSS. The penguins",
    "are afraid to leave their igloos, and they need",
    "Math Command help to keep them safe. Igloos can",
    "protect penguins from Undotrium, but they will",
    "melt if they're hit more than once, and then",
    "the penguin will be without a home. Do not let",
    "that happen!",
    "",
    "-IMPORANT",
    "There is one more thing you should know. Certain",
    "comets are made of a more powerful type of",
    "Undotrium. You will know these comets when you",
    "see them, by their red color. If you can shoot",
    "a red comet, you may be able to use it to build",
    "additional igloos."
    "",
    "",
    "Good luck, Cadet.",
    NULL
  },
  //scout
  {
    "-[Esc] to skip",
    "Mission Two: Smart Scout",
    "------------------------",
    "Great job, Tux. Your performance on FOSS was",
    "brilliant and the penguins give you their thanks.",
    "After such a show of skill and smarts, we feel",
    "that your training as a Cadet must be complete.",
    "We are pleased to promote you to the rank of",
    "Galactic Math Scout. As a gift for your",
    "accomplishment, you are getting your own Lambda",
    "Laser Computer. And it will come in handy...",
    "You need to go on another mission right away!",
    "",
    "Already, another wave of comets is headed toward",
    "FOSS. This time, things will not be so easy.",
    "Radar scans of the new comets show signs of",
    "subtractive Undotrium. Before, you have seen",
    "comets such as \"2+3=5\". Now you will begin to",
    "see \"5-2=3\" and \"5-2=3\". Subtractive",
    "Undotrium is the opposite of normal Undotrium,",
    "just like subtraction is the opposite of",
    "addition. Don't let it trick you!",
    "",
    "Sometimes, you may need to figure out a very",
    "large subtractive comet. The best strategy for",
    "doing so is to start at the lower number and",
    "count upward until you reach the higher number.",
    "The number you count will be the answer, or as",
    "we call it in the Fleet, the difference.",
    "",
    "You can do it, Tux! Show us how good you are.",
    NULL
  },
  //ranger
  {
    "-[Esc] to skip",
    "Mission Three: Royal Ranger",
    "---------------------------",
    "You've done it again. The Penguin Emperor, his",
    "majesty the Great Auk, has heard of your math",
    "skills and wants to congratulate you himself.",
    "You have been invited to the Royal Igloo for a",
    "celebration, where the Emperor will personally",
    "offer a token of gratitude. He tells us it's a",
    "surprise.",
    "",
    "-........",
    "-@**>##;7^^PLEaSe StaND bY",
    "**EMERGENCY ROYAL TRANSMISSION**",
    "-Help! Save us! We....comets.....the penguins...",
    "-...must come to...if....don't....go",
    "**END OF TRANSMISSION**",
    "",
    "It sounds like the Royal Igloo is in trouble.",
    "We weren't able to decode the whole transmission,",
    "but the Emperor definitely said that there were",
    "more comets. We are sending you in right away.",
    "",
    "Intel shows a new strain of Undotrium comets that",
    "are many times larger than the ones you have seen",
    "already. These multiplicative comets are made of",
    "huge amounts of additive Undotrium. To solve them",
    "you will need to add over and over again. Just",
    "one comet can have a question like 3*6, which is",
    "the same as 3+3+3+3+3+3!",
    "",
    "Be careful, Tux. We have also picked up signs of",
    "comets that are very different from the ones",
    "we've seen before. They have numbers that are",
    "less than zero. These negative numbers do",
    "strange things to addition and subtraction. If",
    "a negative number is added, it is really",
    "subtracted, and if it is subtracted, it's really",
    "added.",
    //TODO better explanation of negatives
    "Also, if two numbers are multiplied and one of",
    "them is negative, the answer will be negative",
    "also. But if both numbers are negative, the",
    "answer is positive! Be careful.",
    "",
    "We are making you a Ranger right away, and we",
    "hope that you will give the Emperor and his",
    "citizens extra care. We know you will do so.",
    NULL
  },
  //ace
  {
    "-[Esc] to skip",
    "Mission Four: Imperial Ace",
    "--------------------------",
    "You did it, Tux! The Emperor and the penguins of",
    "FOSS are safe once more. His majesty would like",
    "to speak to you.",
    "",
    "-Please stand by...",
    "**OFFICIAL ROYAL TRANSMISSION**",
    "-Thank you, Tux. The planet FOSS will forever be",
    "-grateful. Please honor us tonight and join our",
    "-celebration. I would like to personally give",
    "-you the designation of imperial Ace. You've done",
    "-well, and you are truly deserving.",
    "**END OF TRANSMISSION**",
    "",
    "Bravo, Tux! The rank of Ace is the highest honor",
    "a Math Command pilot can get. It can only come",
    "from the Emperor himself! We will leave you to",
    "your celebration. When you are finished, there",
    "is more to do. Your mission, should you choose",
    "to accept it, is to end the menace of all these",
    "Mathematican comets once and for all.",
    "",
    "Our scientists have investigated the cause of",
    "the repeated assault of comets: these aren't",
    "coming from Mathematica anymore. A portion of",
    "the original Mathematican asteroids passed",
    "through Recursa Minor, a small but interesting",
    "solar system that multiplies and replicates",
    "anything that comes near it.",
    "",
    "You must travel into Recursa Minor to destroy",
    "the rest of the asteroids before more copies",
    "come out of there and threaten our people. To",
    "make sure there aren't extra copies of YOU,",
    "we will let you borrow the Singleton, an advanced",
    "space ship the Galactic scientists wish to test",
    "out. There should only ever be one Singleton.",
    "",
    "Tux, you will have to destroy asteroids that have",
    "never come out of Recursa Minor: divisive",
    "Undotrium asteroids. Don't be fooled by the",
    "fancy symbol, \"%\". Division is just backwards",
    "multiplication, or repeated subtraction. If you",
    "subtract the divisor (the second number) from",
    "the dividend over and over again, and put up a",
    "finger every time you do, when you hit zero, the",
    "number of fingers you're holding up will be the",
    "answer. It's called the quotient, and it's the",
    "only thing that will let you shoot divisive",
    "Undotrium.",
    "",
    "Finish this, Tux. You're our Ace.",
    NULL
  },
  //commando
  {
    "-[Esc] to skip",
    "Final Mission: Computing Commando",
    "---------------------------------",
    "The penguins came along with you? I see. Those",
    "penguins were copies of the ones from FOSS. The",
    "Singleton was not perfect after all. ",
    "",
    "The ship is yours, Tux. Our scientists need to",
    "start from scratch. Something about not",
    "remembering how to build another Singleton.",
    "",
    "You've done well; there have been no more comet",
    "assaults since you left FOSS. However, there are",
    "still more asteroids deep in Recursa Minor,",
    "orbiting the Moon of Infinite Recursion. The Moon",
    "has mashed different comets into something far,",
    "far nastier than what was originally there.",
    "They're made of different types of Undotrium, and",
    "to destroy them, you will need to figure out the",
    "answer to each type. First to multiplication and",
    "division. Then do addition and subtraction. We",
    "have two examples:",
    "-5*2+7 = 10+7 = 17",
    "-8/4*3*2 = 2*3*2 = 6*2 = 12",
    "Notice that in the first question, we do 5*2=10",
    "first, because multiplication comes before",
    "division.",
    "In the second question, since there is division",
    "and multiplication, we start on the left and go",
    "right. If you go the other way, you will get the",
    "wrong answer!",
    "",
    "This is it, Tux. Succeed here and the galaxy is",
    "safe again. It's time to go Commando.",
    NULL
  },
};

void start_campaign();

#endif // CAMPAIGN_H
